# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fast_foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfoodscore',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
