# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-30 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmark',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
