# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelopinion',
            name='location',
        ),
        migrations.AddField(
            model_name='hotelopinion',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotelopinion',
            name='stars_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of the stars:'),
        ),
        migrations.AddField(
            model_name='hotelopinion',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
