# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180626_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelopinion',
            name='opinion',
            field=models.TextField(default='My opinion goes here...', max_length=400),
            preserve_default=False,
        ),
    ]
