# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotelopinion_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelopinion',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
